- name: 'bug'
  color: 'd73a4a'
  description: '出现了问题需要修复'

- name: 'enhancement'
  color: 'a2eeef'
  description: '新功能或改进请求'

- name: 'documentation'
  color: '0075ca'
  description: '文档相关的改进或修复'

- name: 'dependencies'
  color: '0366d6'
  description: '依赖更新相关'

- name: 'help wanted'
  color: '008672'
  description: '需要帮助'

- name: 'question'
  color: 'd876e3'
  description: '需要更多信息'

- name: 'wontfix'
  color: 'ffffff'
  description: '不会修复的问题'

- name: 'breaking'
  color: 'b60205'
  description: '破坏性更改'

- name: 'good first issue'
  color: '7057ff'
  description: '适合新手的第一个任务'

- name: 'priority: high'
  color: 'd93f0b'
  description: '高优先级'

- name: 'priority: medium'
  color: 'fbca04'
  description: '中等优先级'

- name: 'priority: low'
  color: '0e8a16'
  description: '低优先级'
