run:
    timeout: 5m
    modules-download-mode: readonly
    tests: true
    skip-dirs:
        - hack
        - manifest
    skip-files:
        - ".*_test\\.go$"

linters-settings:
    errcheck:
        check-type-assertions: true
        check-blank: true
    govet:
        check-shadowing: true
    gocyclo:
        min-complexity: 15
    dupl:
        threshold: 100
    goconst:
        min-len: 3
        min-occurrences: 3
    revive:
        confidence: 0.8
    goimports:
        local-prefixes: github.com/kysion/base-library
    gocritic:
        enabled-tags:
            - diagnostic
            - style
            - performance
            - experimental
            - opinionated
    gosec:
        exclude-generated: true
        excludes:
            - G104 # Audit errors.go not checked
    gofmt:
        simplify: true
    unused:
        check-exported: false
    stylecheck:
        checks:
            - '-ST1003' # 禁用字段命名规范检查（如 Id 应为 ID）
            - '-ST1000' # 禁用包注释检查

linters:
    enable:
        - bodyclose
        - depguard
        - dogsled
        - dupl
        - errcheck
        - gochecknoinits
        - goconst
        - gocritic
        - gocyclo
        - gofmt
        - goimports
        - gosec
        - gosimple
        - govet
        - ineffassign
        - misspell
        - nakedret
        - prealloc
        - revive
        - staticcheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - whitespace
    disable:
        - deadcode # 已废弃的检查器
        - structcheck # 已废弃的检查器
        - varcheck # 已废弃的检查器
        - funlen
        - gomnd
        - gocognit
        - lll
        - godox
        - gochecknoglobals
        - wsl

issues:
    exclude-rules:
        # 测试文件排除
        - path: _test\.go
          linters:
              - dupl
              - gosec
              - goconst
        # 忽略特定目录或文件
        - path: utility/command/command.go
          linters:
              - gosec
        - path: utility/base_tree/
          linters:
              - stylecheck
              - unused
        - path: utility/f_sql/
          linters:
              - structcheck
              - unused
              - stylecheck
        - path: utility/downloader/
          linters:
              - typecheck
        - path: utility/format_utils/
          linters:
              - typecheck
        - path: base_model/base_enum/
          linters:
              - typecheck
        # 忽略特定错误
        - text: 'G104:'
          linters:
              - gosec
        - text: 'G204:'
          linters:
              - gosec

    max-issues-per-linter: 0
    max-same-issues: 0
    fix: true
    exclude-use-default: false
    exclude-dirs:
        - hack
        - manifest
