name: 文档生成

on:
    push:
        branches:
            - main
            - dev
        paths:
            - '**.go'
            - '**.md'
            - 'docs/**'
    workflow_dispatch:

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: 设置 Go 环境
              uses: actions/setup-go@v4
              with:
                  go-version: '1.24.1'

            - name: 安装 godoc
              run: go install golang.org/x/tools/cmd/godoc@latest

            - name: 生成文档
              run: |
                  mkdir -p docs/api
                  godoc -url=/pkg/github.com/kysion/base-library > docs/api/index.html

            - name: 提交文档更新
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add docs/
                  git commit -m "docs: 自动更新 API 文档" || echo "No changes to commit"
                  git push
