name: 通知依赖库更新

on:
    release:
        types: [published]
    workflow_dispatch:
        inputs:
            version:
                description: '指定版本号（不填则使用最新版本）'
                required: false
                type: string

env:
    TZ: Asia/Shanghai
    # 需要通知的仓库列表
    DEPENDENT_REPOS: |
        kysion/sms-library
        kysion/oss-library
        kysion/gf-admin-community

jobs:
    notify-dependents:
        name: 通知依赖库更新
        runs-on: ubuntu-latest
        strategy:
            matrix:
                repo: ${{ fromJson(env.DEPENDENT_REPOS) }}
            # 允许单个仓库失败不影响其他仓库
            fail-fast: false

        steps:
            - name: 获取版本信息
              id: version
              run: |
                  if [ -n "${{ github.event.inputs.version }}" ]; then
                      echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
                  else
                      echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
                  fi

            - name: 触发依赖库更新
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GH_PAT }}
                  script: |
                      const repo = '${{ matrix.repo }}'.split('/');
                      const owner = repo[0];
                      const repoName = repo[1];
                      const version = '${{ steps.version.outputs.version }}';

                      try {
                          // 触发依赖库的工作流
                          await github.rest.actions.createWorkflowDispatch({
                              owner: owner,
                              repo: repoName,
                              workflow_id: 'update-deps.yml',
                              ref: 'dev',
                              inputs: {
                                  force_update: 'true',
                                  base_version: version
                              }
                          });
                          
                          console.log(`成功触发 ${owner}/${repoName} 的更新工作流`);
                          
                          // 创建议题通知
                          const issueBody = `
                          # 依赖更新通知
                          
                          base-library 已发布新版本 ${version}，请注意更新。
                          
                          ## 自动化操作
                          - 已触发自动更新工作流
                          - 请检查更新是否成功
                          - 如需手动更新，请运行 update-deps 工作流
                          
                          ## 相关链接
                          - [新版本发布页面](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/releases/tag/${version})
                          - [更新工作流状态](${process.env.GITHUB_SERVER_URL}/${owner}/${repoName}/actions/workflows/update-deps.yml)
                          `;
                          
                          await github.rest.issues.create({
                              owner: owner,
                              repo: repoName,
                              title: `依赖更新: base-library ${version}`,
                              body: issueBody,
                              labels: ['dependencies', 'automated']
                          });
                          
                      } catch (error) {
                          console.error(`触发 ${owner}/${repoName} 更新失败:`, error);
                          throw error;
                      }

            - name: 检查更新状态
              if: success()
              run: |
                  echo "已成功通知 ${{ matrix.repo }} 更新依赖"
                  echo "版本: ${{ steps.version.outputs.version }}"

            - name: 通知失败处理
              if: failure()
              run: |
                  echo "通知 ${{ matrix.repo }} 失败"
                  echo "请手动检查并触发更新"
